// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories.get').default>>>>
    }
    '/api/migrate/categories': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/categories.post').default>>>>
    }
    '/api/migrate/products': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/products.post').default>>>>
    }
    '/api/migrate/sales': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/sales.post').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products.get').default>>>>
    }
    '/api/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales.get').default>>>>
    }
  }
}
export {}