// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories.post').default>>>>
    }
    '/api/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories/[id].put').default>>>>
    }
    '/api/migrate/categories': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/categories.post').default>>>>
    }
    '/api/migrate/products': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/products.post').default>>>>
    }
    '/api/migrate/sales': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/sales.post').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products.post').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products/[id].put').default>>>>
    }
    '/api/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales.post').default>>>>
    }
    '/api/test-db': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/test-db.get').default>>>>
    }
  }
}
export {}