// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cash-register': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/cash-register.get').default>>>>
    }
    '/api/cash-register/close': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/cash-register/close.post').default>>>>
    }
    '/api/cash-register/open': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/cash-register/open.post').default>>>>
    }
    '/api/cash-transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/cash-transactions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/cash-transactions.post').default>>>>
    }
    '/api/cash-transactions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/cash-transactions/[id].delete').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories.post').default>>>>
    }
    '/api/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/categories/[id].put').default>>>>
    }
    '/api/contingency': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/contingency.get').default>>>>
    }
    '/api/contingency/:id/retry': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/contingency/[id]/retry.post').default>>>>
    }
    '/api/customers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/customers.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/customers.post').default>>>>
    }
    '/api/customers/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/customers/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/customers/[id].put').default>>>>
    }
    '/api/customers/:id/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/customers/[id]/sales.get').default>>>>
    }
    '/api/fiscal/certificates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/certificates.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/certificates.post').default>>>>
    }
    '/api/fiscal/certificates/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/certificates/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/certificates/[id].patch').default>>>>
    }
    '/api/fiscal/company-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/company-config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/company-config.post').default>>>>
    }
    '/api/fiscal/test-connection': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/fiscal/test-connection.post').default>>>>
    }
    '/api/migrate/categories': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/categories.post').default>>>>
    }
    '/api/migrate/products': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/products.post').default>>>>
    }
    '/api/migrate/sales': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/migrate/sales.post').default>>>>
    }
    '/api/motoboys': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/motoboys.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/motoboys.post').default>>>>
    }
    '/api/motoboys/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/motoboys/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/motoboys/[id].put').default>>>>
    }
    '/api/nfce': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfce.get').default>>>>
    }
    '/api/nfce/:id/qr-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfce/[id]/qr-code.get').default>>>>
    }
    '/api/nfce/:sale_id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfce/[sale_id].get').default>>>>
    }
    '/api/nfce/emitir': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfce/emitir.post').default>>>>
    }
    '/api/nfce/xml/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfce/xml/[id].get').default>>>>
    }
    '/api/nfe': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfe.get').default>>>>
    }
    '/api/nfe/:saleId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfe/[saleId].get').default>>>>
    }
    '/api/nfe/emitir': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfe/emitir.post').default>>>>
    }
    '/api/nfe/xml/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/nfe/xml/[id].get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products.post').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/products/[id].put').default>>>>
    }
    '/api/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales.post').default>>>>
    }
    '/api/sales/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales/[id]/status.put').default>>>>
    }
    '/api/sales/:id/xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/sales/[id]/xml.get').default>>>>
    }
    '/api/test-db': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/test-db.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/upload.post').default>>>>
    }
  }
}
export {}